### ISSUE TITLE
Pymoca doesnot ignore annotation correctly

### ISSUE THREAD

**Issue by MaartenSmoorenburg** [pymoca/pymoca#135]
It failed on this annotation:
/* definition of the OMedit canvas */
  annotation(
    Diagram(coordinateSystem(extent = {{-100, -100}, {360, 100}}, initialScale = 0.1), graphics = {Bitmap(origin = {95, 225}, extent = {{-359, 203}, {295, -123}}, fileName = "modelica://DRAU/overview.jpg")}),
    Icon(coordinateSystem(extent = {{-100, -100}, {360, 100}})),
    version = "",
    uses,
    __OpenModelica_commandLineOptions = "");

**Comment by jackvreeken** [comment]
Fixed with 7c0a73d37b2d5ea92a14c5d8794cb1a1f9136dfe
