### ISSUE TITLE
Falls on reading Library annotations

### ISSUE THREAD

**Issue by Stamp1993** [pymoca/pymoca#146]
Throws 
```
line 169:185 mismatched input ';' expecting ':'
line 184:72 mismatched input ';' expecting ':'
line 199:72 mismatched input ';' expecting ':'
line 214:72 mismatched input ';' expecting ':'
```
On all Library annotations
`annotation (Library={"ModelicaStandardTables", "ModelicaMatIO", "zlib"});`

Other types of annotations don't cause this error

**Comment by jackvreeken** [comment]
Tried it in various places, but parses and flattens just fine here:

```Modelica
model A
    Real x, y annotation(Library={"ModelicaStandardTables", "ModelicaMatIO", "zlib"});
equation
    x = 2 * y annotation(Library={"ModelicaStandardTables", "ModelicaMatIO", "zlib"});
	annotation(Library={"ModelicaStandardTables", "ModelicaMatIO", "zlib"});
end A;
```

Looking at your error message, you did something the grammar does not allow. Could you paste a (simplified) version of your model here to reproduce the error?

**Comment by Stamp1993** [comment]
Is this more useful? This throws the same error at the same place.

```
package test
package Utilities
   block CombiTable2D "Table look-up in two dimensions (matrix/file)"
     extends Modelica.Blocks.Interfaces.SI2SO;
     function readTableData "Read table data from ASCII text or MATLAB MAT-file"
       extends Modelica.Icons.Function;
       input Modelica.Blocks.Types.ExternalCombiTable2D tableID;
       input Boolean forceRead = false "= true: Force reading of table data; = false: Only read, if not yet read.";
       input Boolean verboseRead "= true: Print info message; = false: No info message";
       output Real readSuccess "Table read success";
       external "C" readSuccess = ModelicaStandardTables_CombiTable2D_read(tableID, forceRead, verboseRead)
       annotation (Library={"ModelicaStandardTables", "ModelicaMatIO", "zlib"});
       annotation(
         __ModelicaAssociation_Impure = true);
     end readTableData;
   end CombiTable2D;
end Utilities;
end test;
```

**Comment by jackvreeken** [comment]
OK, so the grammar on that is wrong. We have `ext_annotation=annotation? ':')?` (line 82 in Modelica.g4), which should be `ext_annotation=annotation? ';')?` (at least according to section 12.9 of the Modelica spec v3.4). I will fix that.

Aside from that, it seems that you are using functionality that Pymoca does not support yet as far as I know (external functions). I am not entirely sure what you want to do with Pymoca, but it is currently very much aimed at translating from Modelica to CasADi for the specific needs of RTC-Tools.

**Comment by Stamp1993** [comment]
Thank you.

And thank you for the warning about external functions too. I'll check what I can do with it then.
