### ISSUE TITLE
Add file extension for cached models

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#154]
Currently we save a cached model "Test" as a file "Test", possibly with additional dll/so files next to it if codegen is enabled. It would be nice if we could add an extension to those pickle files, such that:
1. It is clear what they are (i.e. a pickle cache)
2. People can ignore them easily in .gitignore files
3. Easy removal with wildcards 

Because model names are typically not excessively long, I propose to just use a descriptive `<model name>.pymoca_cache`.

**Comment by AnneHommelberg** [comment]
Since the files are a pickle cache and theoretically any other program could "unpickle" them, I'd go for the more general <model name>.cache or <model name>.pickle_cache.

**Comment by jackvreeken** [comment]
I agree with that, but after a bit of pondering I feel that it being a pickle is an implementation detail. The generic ".cache" option is possible, but with .gitignore files in mind I feel that is a bit _too_ generic. With pytest calling its cache folder ".pytest_cache" as well, I think ".pymoca_cache" will be a good one.
