### ISSUE TITLE
detect_aliases overwrite non default starting values without prompting the user

### ISSUE THREAD

**Issue by PeterRabbit95** [pymoca/pymoca#208]
When detecting and eliminating aliases in the casadi model_transfer api the start value of the possibly non-default canonical state start value is ignored as soon as one of the aliases has a non-default start value

``` python
# If any of the aliases has a nondefault start value, apply it to
# the canonical state as well
alias_state_start = ca.MX(alias_state.start)
if not alias_state_start.is_constant() or not alias_state_start.is_zero():
     start = sign * alias_state.start
```

Imho the start value of the canonical variable should have the precedence over the aliases and maybe we should warn the user that non-default start values of the aliases have been ignored. 

We could do something like:

``` python
# If any of the aliases has a nondefault start value, apply it to
# the canonical state as well
alias_state_start = ca.MX(alias_state.start)
# check if the alias has a non-deault start value
if not alias_state_start.is_constant() or not alias_state_start.is_zero():
    # check if a non-default value was already present
    if not ca.MX(start).is_constant() or not ca.MX(start).is_zero():
        # check if the value is not the same
        if start != alias_state.start:
            # prompt the user that alias start value has been ignored
            logger.info("Non-default starting value for alias {} ignored.".format(alias))
    else:
        start = sign * alias_state.start
```

I found this particularly important when using units from the modelica standard library that have a starting values set. 

PS: please forgive me if this is not the way to public issues, I am quite new to cooperating on github. Maybe I should have opened a pull request? I am ready to accept any suggestion!

**Comment by jackvreeken** [comment]
Thanks for the suggestion! I definitely agree we should warn if aliases have different start values. I'll see if I can whip something up based on your suggestion (and include a test of course 😃).
