### ISSUE TITLE
multiple calls to model simplify with casadi backend are risky

### ISSUE THREAD

**Issue by PeterRabbit95** [pymoca/pymoca#214]
Calling model simplify more than once (including the implicit call during model building) can be risky due to issues mainly caused by alias detection. 

Multiple calls to the model simplification process can be beneficial to reduce the number of equations especially when alternating detect_aliases and eliminate_constant_assignments. Unfortunately, this might often raise errors:

One scenario is when two calls of detect_aliases are made.

Consider the following simple model:

```modelica
model AlgStates

Real x1(start = 0);
Real x2(start = 0);
Real z;
Real f;
input Real u(min = -5, max = 10);
input Real u1(min = -5, max = 100);

equation

der(x2) = x1 + u1;
der(x1) = u + z;
f = 0.2;
z = f;

end AlgStates;
```

On the second call to detect_aliases it will raise an error because the variable z won't be amongst the model variables anymore.

A possible solution to this is changing (in model.py)
```python
alias_state = all_states[alias]
```
with
```python
try:
    alias_state = all_states[alias]
    logger.debug("Detecting aliases: merging info from {} to {}".format(alias, canonical))
except KeyError:
    logger.debug("Detecting aliases: alias {} is not available. Probably you are calling simplify 
again".format(alias))
    continue
```

Another scenario is when there is the following call chain: detect_aliases, eliminate_constant_assignments and detect_aliases.

The risk here is that eliminate_constant_assignments eliminates a canonical variable created by the first detect_aliases.

Imho we should decide whether to allow multiple calls to simplify (and in this case, we should improve the robustness, e.g with checks similar to the one I proposed) or whether not to allow them (and in this case, a single call should be more effective)

**Comment by jackvreeken** [comment]
Do you have any preference for which one to prefer? I think until now I just assumed that additional simplify() calls would just be noops, but apparently they are not.

**Comment by PeterRabbit95** [comment]
I did not have time to implement anything but I feel like the easiest path is to make simplify more robust and allow multiple calls. I'll try to play around tomorrow. Furthermore, I would even implement a 'simplify_recursive' option where the user can define a number of calls to be implicitly made. We could then probably check if there is actually any change and in case there isn't stop the process earlier.
