### ISSUE TITLE
Cite pymoca in scientific research

### ISSUE THREAD

**Issue by pietropelizzari** [pymoca/pymoca#224]
I am using pymoca in the context of my master thesis in mechanical engineering and I was wondering if there is a preferable way to cite it

**Comment by jackvreeken** [comment]
Well, @jgoppert once made this commit for a DOI https://github.com/pymoca/pymoca/commit/31365bdabbd31297b72cb7574f0c5d796e71e1a1 . I don't know if he also actually cited it somewhere. Otherwise, whatever you come up with is the defacto standard I guess 😜

**Comment by jgoppert** [comment]
Yes, I cited it via the DOI for several proposals.

**Comment by pietropelizzari** [comment]
Thanks for the feedback! I'll use the DOI then
