### ISSUE TITLE
(Automatically) upload sdist + bdist_wheel to PyPI

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#24]
There is already a PyPI page for Pymola (which has not been updated in a while). The Cythonizing of the parser makes installing pymola a bit more demanding for users, as it requires a (usable) compiler being present on their systems. So instead I was thinking of maybe publishing binary wheels as well.

One more reason for the timing of me making this is issue is (from what I can tell) that scipy is relatively close to publishing binary wheels for all platforms. It would be awesome if users could just do a `pip install pymola`, even on Windows (which used to require further manual action), with no other requirement than having Python installed.

**Comment by jackvreeken** [comment]
I did some speed tests, and I do not think the Cythoning adds much. I remember it doing so way back when, but now there is barely any difference. That means testing Linux + Mac (?) + Windows, and then publishing a source wheel (for tags) should be sufficient.

**Comment by jgoppert** [comment]
I'd also support removing the cython bit, makes it too hard for users.

**Comment by jackvreeken** [comment]
Alright, I will work on that as well then. I have been trying some stuff out over at [my fork](https://github.com/jackvreeken/pymola). The way I see it, to get this issue and #8 resolved, the following steps are needed:
1. Merge changes from jbaayen/pymola (or my fork) back into here. A lot has happened in the last few months, but I want to wait for the release of Casadi 3.3 wheels for the merge. Have you been working ont he Sympy end (i.e. will I possibly break things by merging)?
2. Use tox to test on Travis (Python 3.5 and 3.6 for Linux, latest Python for MacOS), and AppVeyor (Windows Python 3.5 & Python 3.6, both 32-bit and 64-bit platforms). Again, busy playing with that on [my fork](https://github.com/jackvreeken/pymola). When this works, merge it.
3. Add auto-uploading of sdist and bdist_wheel from Travis to PyPI for tags. This will require adding e.g. a `pymola.wheelhouse` user to PyPI, which you will then have to grant rights over at PyPI.
4. Update README.md (step 1 & 2 --> "pip install pymola")

Furthermore, I was wondering what your thoughts were on the Conda stuff that is in the repository now, as step 2 above as I implemented it now will effectively remove that. Do you prefer conda over pip, or was it just needed to get it to work?

**Comment by jackvreeken** [comment]
Alright, with CasADi 3.3 released I made a merge request #26 to address item 1 in my post above.

**Comment by jackvreeken** [comment]
Item 2 was addressed in #27

**Comment by jackvreeken** [comment]
Looking at https://travis-ci.org/pymoca/pymoca/jobs/351411914 ,  apparently the automatic deploy failed (so you uploaded manually @jgoppert ?).

Futhermore, do you still use conda? I would like to amend the README to mentioned PyPI / `pip install pymoca` as well, and then close this issue.

**Comment by jgoppert** [comment]
I didn't realize we had an auto upload setup, so I just did: python setup.py sdist upload

I do still use conda, but I think pip instructions should be on there as well. 

We might want to consider https://conda-forge.org/  I've used it for another package and it is great. Will take a bit of setup though.

**Comment by jackvreeken** [comment]
OK, so apparently I didn't quite understand how TravisCI works. I had to use the beta feature (which has been there for almost a year now?) to support stages. Basically, we only want to deploy if all tests succeed (and only for tags of course). What happened before was that _all_ tests tried to deploy after they succeeded, so all but one of them would fail doing so (because you can't reupload the same version number twice for obvious reasons).

As far as Conda packaging is concerned, I would like to leave that up to you. I have always used the "official" Python ecosystem like pip and PyPI, and never used any Anaconda installations.
