### ISSUE TITLE
Modelica time is not supported by the SymPy backend

### ISSUE THREAD

**Issue by dospes** [pymoca/pymoca#256]
As discussed in #255, the Modelica Reference to the simulation time is not supported by the SymPy backend. In a flat Modelica model, the time variable may be used in generators, such as line 12 from the attached example:
`sine__y = sine__offset + sine__amplitude * sin(6.283185307179586 * sine__f * time + sine__phase);`
The time variable will not be defined in the declaration section of the model/class when compiling the MO file to an MOF file via omc and is thus not part of the symbols in the ast. The pymoca.sympy.generator creates a time variable "t", but does not link the "time" variable, that is present in the ast only in the equations but not as a symbol, to this variable "t". Possible solutions are:
1. The inclusion of "time" in the list of symbols of the ast, in every case or only when it is used in an equation, or
2. The declaration of a time variable in pymoca.sympy.generator, which would then be somehow linked to the variable "t", created in the pymoca.sympy.runtime.OdeModel class (an easy but inelegant way could be to create a state or variable for "time" in exitClass() in pymoca.sympy.generator and then linking it to "t" within SymPy by symbolic equivalence).

**Comment by dospes** [comment]
What I have found is that the time issue can easily be fixed by including this line
`time = sp.Symbol('t')`
before executing the generated sympy source code. To fix the issue, this line could be added to the jinja template for OdeModel.

**Comment by kentrutan** [comment]
Will you please attach your current example? I have a fix for this that I would like to test.

**Comment by dospes** [comment]
See here. The MOF file has been edited (from the original MOF file obtained with the OpenModelica compiler) to remove the stateSelection related lines and arguments. Line 18 fixes the time problem, so remove it to test your fix.

[example.zip](https://github.com/pymoca/pymoca/files/10155005/example.zip)
