### ISSUE TITLE
MacOS testing on Travis is very slow

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#29]
There are generally quite large queues on the [status page](https://www.traviscistatus.com) for MacOS. We also are only able to test the latest version of Python, as it is quite difficult to get a consistent version of Python (except by using MacPython, which I feel is not ideal).

So where Linux builds on Travis finish in ~3 minutes (because parallel), and those on AppVeyor take about 3 minutes each (so 12 minutes total), the test for MacOS can easily take an hour to even start.

I really want to test for all major platforms (which is why I added it), but with these runtimes I feel it's not worth it. Maybe we can enable it again when a better service becomes available, e.g. when Apple starts allowing/supporting MacOS to run on non-Apple hardware (likely never).

**Comment by jgoppert** [comment]
This seems to be resolved now.
