### ISSUE TITLE
Error in 0.10.0 when setting alias type

### ISSUE THREAD

**Issue by SGeevers** [pymoca/pymoca#300]
Pymoca 0.10.0 transfer_model seems to crash when setting an alias type.

Minimal example: a package file
```Modelica
package Package
  type Length = Real;
  type Height = Length;
end Package;
```
with submodel
```Modelica
model SubModel
  input Package.Height H;
end SubModel;
```
and model
```Modelica
model Model
  SubModel var(H=5);
equation
  // var.H = 5;
end Model;
```
and python file
```python
from pathlib import Path
import pymoca.backends.casadi.api

model_folder = Path(__file__).resolve().parent

model = pymoca.backends.casadi.api.transfer_model(model_folder, "Model")
```
all in the same folder. When running the python file with python 3.9, pymoca 0.10.0, casadi 3.6.3, it gives the following error message:

> pymoca.tree.ModificationTargetNotFound: Trying to modify symbol value, which does not exist in class Package.Height

It works fine when replacing `Height` with `Length` in the submodel file. It also works fine when replacing `var(H=5)` with `var` and uncommenting the equation in the model file.

**Comment by jackvreeken** [comment]
@kentrutan You last worked on this in https://github.com/pymoca/pymoca/commit/4dd90480f59b408baa858bd0cea7983e6176f546 , any ideas?

**Comment by kentrutan** [comment]
@SGeevers thanks for taking time to report with a very specific test case! 🥇 This should be fixed in the next release. Let us know how urgent it is for you.

@jackvreeken thanks for pointing me to the related commit.
