### ISSUE TITLE
sympy.Functions in Spring.ipynb

### ISSUE THREAD

**Issue by gdmcbain** [pymoca/pymoca#326]
https://github.com/pymoca/pymoca/blob/9d597d76aa2b82bd3d563d4938a098af8baafd49/test/notebooks/Spring.ipynb#L1463

raises

```txt
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[32], [line 2](vscode-notebook-cell:?execution_count=32&line=2)
      [1](vscode-notebook-cell:?execution_count=32&line=1) v_x, spring_k, t, V, x = sympy.symbols('v_x, spring.k, t, V, x')
----> [2](vscode-notebook-cell:?execution_count=32&line=2) V_eq = (v_x(t)**2 + spring_k*x(t)**2)/2
      [3](vscode-notebook-cell:?execution_count=32&line=3) sympy.Eq(V, V_eq)

TypeError: 'Symbol' object is not callable
```

**Comment by gdmcbain** [comment]
Maybe they should be redefined  with [`sympy.Function`](<https://docs.sympy.org/latest/modules/functions/>)?

```python
v_x = sympy.Function('v_x')
x = sympy.Function('x')
V = sympy.Function('V')
spring_k, t = sympy.symbols('spring.k, t')
V_eq = (v_x(t)**2 + spring_k*x(t)**2)/2
sympy.Eq(V(t), V_eq)
```

That works:

![image](https://github.com/pymoca/pymoca/assets/1588947/a78a3b58-c310-4c2b-a48c-85732c2e59b9)

and in subsequent cells through to the plot of the history of the candidate Lyapunov energy function.

**Comment by kentrutan** [comment]
@gdmcbain I finally got around to using your suggestions to update Spring.ipynb. Thanks for taking the time to document the fix. Should be in the upcoming release.
