### ISSUE TITLE
CasADi: CI fail on Windows in gen_casadi_test.py `test_codegen`

### ISSUE THREAD

**Issue by kentrutan** [pymoca/pymoca#338]
In CI on the Windows environments, we are getting the following compile errors in a file generated by CasADi 3.6.7. This version of CasADi was released Sept. 30, 2024 and there were successful Windows CI runs with this version until the first failure Nov. 20. There was a change in the Windows image between these dates.

```
test\models\Aircraft_variable_metadata.c(144): error C2099: initializer is not a constant
test\models\Aircraft_variable_metadata.c(145): error C2099: initializer is not a constant
```

These are the offending lines of Aircraft_variable_metadata.c generated on macOS:

```C
static const casadi_real casadi_c0[6] = {casadi_nan, casadi_nan, -casadi_inf, -casadi_inf, casadi_inf, casadi_inf};
static const casadi_real casadi_c1[18] = {casadi_nan, casadi_nan, casadi_nan, casadi_nan, casadi_nan, casadi_nan, -casadi_inf, -casadi_inf, -casadi_inf, -casadi_inf, -casadi_inf, -casadi_inf, casadi_inf, casadi_inf, casadi_inf, casadi_inf, casadi_inf, casadi_inf};
```

I don't have a Windows machine to debug this.

**Comment by kentrutan** [comment]
Suggestions on this one @jackvreeken?

**Comment by jackvreeken** [comment]
I'll take a look next week. See if I can reproduce it locally, and possibly see what causes it over on the casadi side. There's a few issues on the casadi side about codegen, but none covering this (yet) as far as I can tell

**Comment by jackvreeken** [comment]
Quick update (no fix yet). I couldn't reproduce by updating MSVC on my PC from 14.38.33130 to 14.42.34433 . 

Then I noticed I had Windows SDK version 10.0.22621.0 . Updating to 10.0.26100.0 resulted in the error. The only relevant include is `math.h`, so I had a look there (two diff sections, below is the relevant one):

```diff
--- 10.0.22621.corecrt_math.h	Sun Sep 24 14:22:04 2023
+++ 10.0.26100.corecrt_math.h	Tue Dec  3 18:40:24 2024
@@ -81,20 +81,43 @@
     #endif
 #endif
 
+#if !defined __cplusplus && !defined __midl 
+inline float __ucrt_int_to_float(int i)
+{
+    union {
+        int i;
+        float f;
+    } __my_int_to_float;
+
+    __my_int_to_float.i = i;
+    return __my_int_to_float.f;
+}
+#endif
+
 #ifndef _HUGE_ENUF
     #define _HUGE_ENUF  1e+300  // _HUGE_ENUF*_HUGE_ENUF must overflow
 #endif
-
+#ifndef _UCRT_LEGACY_INFINITY
+#define INFINITY   ((float)(_HUGE_ENUF))
+#else
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
+#endif
 #define HUGE_VAL   ((double)INFINITY)
 #define HUGE_VALF  ((float)INFINITY)
 #define HUGE_VALL  ((long double)INFINITY)
-#ifndef _UCRT_NEGATIVE_NAN
-// This operation creates a negative NAN adding a - to make it positive
-#define NAN        (-(float)(INFINITY * 0.0F))
+
+#if defined _UCRT_NOISY_NAN || defined __midl
+#define _UCRT_NAN (-(float)(((float)(_HUGE_ENUF * _HUGE_ENUF)) * 0.0F))
+#elif defined __cplusplus
+#define _UCRT_NAN (__builtin_nanf("0"))
 #else
-// Keep this for backwards compatibility
-#define NAN        ((float)(INFINITY * 0.0F))
+#define _UCRT_NAN (__ucrt_int_to_float(0x7FC00000))
+#endif
+
+#ifdef _UCRT_NEGATIVE_NAN
+#define NAN (-_UCRT_NAN)
+#else
+#define NAN _UCRT_NAN
 #endif
 
 #define _DENORM    (-2)
```

So it's the NaN. This also makes it easy to google for, and we end up with https://stackoverflow.com/questions/79195142/recent-msvc-versions-dont-treat-nan-as-constant-workaround
