### ISSUE TITLE
Cannot distinguish between 1-element array and scalar symbols

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#44]
Currently we cannot properly distinguish after parsing/flattening whether a symbol was a 1-element array or a scalar. Example:

```Modelica
model Test
    parameter Integer n = 1;
    Real w[n];
    Real x[1];
    Real y;
    Real z[1,1];
end Test;
```

This matters when we have to name the symbols (e.g. in the CasADi backend when expanding vectors/arrays), such that they can then later be referenced by the user. The user would expect, based on the above Modelica code, that a symbol `x[1]` and a symbol `y` exist. But both have the same signature, which is `sym.dimensions = [1]`.

As it turns out, currently ```symbols['y'].dimensions[0]``` is a `Primary` of with a `value` field of type *int*, whereas `x` is similar but has a *float* inside. So strictly speaking we can distinguish scalars from 1-element arrays, but I would much rather have `.dimensions = []` or `.dimensions = None`, such that we can do a `if not sym.dimensions` in the Python code to detect scalars.

For deeply nested arrays (of arrays, of arrays), I would think of something like `.dimensions = [1, 2, None, 1, None]`. That would however complicate a lot of code, so we could also just opt for the int vs. float approach (or making a custom type "ScalarElementIndex" that is equal to 1). I'm very much open for suggestions.

**Comment by jackvreeken** [comment]
If None does not work well (i.e. results in too many if-else clauses in the `tree.py`), something like below might work well.
```python
class ScalarDimension(int):
    def __new__(cls, *args, **kwargs):
        return  super(ScalarDimension, cls).__new__(cls, 1)
```

**Comment by AnneHommelberg** [comment]
fixed by https://github.com/pymoca/pymoca/pull/153/commits/37246e4bffdc79d1c05d1be3a5df83b288b1ee88
