### ISSUE TITLE
Cannot pair nested array symbols to their dimensions

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#45]
During flattening we move the dimensions always to the last symbol. This simplifies a lot of things, but does result in not being able to properly name nested arrays symbol later. For a related issue, see #44 .

Example:
```Modelica
model A
    Real x[3];
end A;

model B
    A a[3];
end B;

model C
    B b;
end C;

model D
    C c[2];
end D;

model Test
    D d;
end Test;
```

Results in a symbol `d.c.b.a.x` with dimensions `[2, 3, 3]`. We would like to be able to figure out what dimension belongs to what nested element, such that the user can refer to a symbol named `d.c[1].b.a[2].x[3]` instead of `d.c.b.a.x[1, 2, 3]`. That means we have to store scalar element dimensions in a distinguishable way (see #44), such that we end up with something like `dimensions = [None, 2, None, 3, 3]` or `dimensions = [/1/, 2, /1/, 3, 3]` where `/1/` is of a special (scalar signifying) type.

**Comment by AnneHommelberg** [comment]
fixed by https://github.com/pymoca/pymoca/pull/153/commits/37246e4bffdc79d1c05d1be3a5df83b288b1ee88
