### ISSUE TITLE
Trademark Issue

### ISSUE THREAD

**Issue by xogeny** [pymoca/pymoca#88]
I suspect you may want to rename this project.  I grant you that the name is clever and I wish you nothing but the best of luck.  But the fact that Dymola is trademarked by a large company with very deep pockets would make me hesitant to give a project, which is very much in a related area, a name that is only one letter difference.

The thing is, the nature of trademark law is such that they have almost no choice but to step in (if they find out about this project) because they can lose their trademark if they don't take steps to defend it.  So if they do [come knocking](https://en.wikipedia.org/wiki/Kik_Messenger#Open-source_module_name), just be aware that it isn't (necessarily) that they are trying to be difficult.

**Comment by jgoppert** [comment]
@xogeny Thanks for the heads up. I'm fine with renaming, we can start thinking up some ideas.

pymodelica is already used unfortunately.

* pymelica
* pymodla
* pymolica
* pymolica <-- kind of like this

**Comment by jbaayen** [comment]
Prior to discovering pymola, we considered calling our Modelica-to-CasADi project '**m**o**c**a'.

**Comment by jbaayen** [comment]
'mosym' also sounds nice imo.

**Comment by jackvreeken** [comment]
A +1 from me for pymolica.

I suggest not waiting too long with a renaming, as the impact of doing so would only get larger. Preferably we would do it as soon as possible.

**Comment by jbaayen** [comment]
Agree we should do this asap.

pymolica sounds nice but is easy to confuse with pymodelica for sloppy readers like myself.

**Comment by jgoppert** [comment]
Any objections to running with pymoca?   Seems short, one letter change, and can be generalized to Python MOdelica -> Computer Algebra system

**Comment by vdwees** [comment]
+1 for pymoca

**Comment by jgoppert** [comment]
@jbaayen @jackvreeken pymoca work for you?

**Comment by jackvreeken** [comment]
Yep, fine by me. Moca/mocha is used by everyone and their dog (but no one in the Modelica world afaik), so I doubt we would have a trademark issue there.

**Comment by jgoppert** [comment]
OK, should I go ahead an change the orgnaization and project name? We can worry about refactoring the code after that.

**Comment by jgoppert** [comment]
Rename complete, I created a new branch for rename of the source code to see if it broke anything.
